<a href="https://colab.research.google.com/github/omidr1348/traffic/blob/main/traffic_shahri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ترافیک شهری
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ترافیک شهری به یکی از بزرگترین معظلات شهرنشینان تبدیل شده است. شما هم اگر ساکن شهرهای بزرگی مثل تهران، مشهد و اصفهان باشید، حتما بخش زیادی از وقتتان را در ترافیک گذرانده‌اید.
    <br>
     اما اتلاف وقت، تنها یکی از چندین و چند ضرری است که عدم کنترل و بی‌برنامگی ترافیک به‌بار می‌آورد. افزایش مصرف حامل‌های انرژی، آلودگی هوا و مشکلات  روانی تنها بخشی از آسیب‌های عدم مدیریت ترافیک شهری هستند.
    <br>
    بافت قدیمی شهر‌ها، استاندارد نبودن مسیرها، ضعف سیستم‌های کنترلی مثل چراغ‌های راهنمایی، عدم توازن ناوگان حمل‌ونقل عمومی، از جمله عواملی هستند که روی افزایش ترافیک شهری تاثیر می‌گذارند.
    <br>
    در این تمرین می‌خواهیم به شهرداری کمک کنیم در مدیریت ترافیک شهری، موفق‌تر عمل کند.
    <br>
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در این تمرین، اطلاعاتی را از ۴ چهار‌راه در کلانشهر اصفهان در اختیار داریم. دوربین‌های سر هر چهارراه، تعداد ماشینی که در هر ساعت شبانه‌روز از چهارراه گذر کرده است را شمرده اند. بنابراین مجموعه داده ما به شکل جدول زیر است.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|DateTime|زمان ثبت رکورد|
|Junction|شماره چهارراه|
|Car|تعداد ماشین‌های گذرکرده|
    
</font>
</div>



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
 اطلاعات هر چهارراه از اولین ساعت شبانه‌روز تا ساعت پایانی روز، به مدت چندین ماه، ثبت و ضبط شده است. به عنوان مثال تعداد ماشین‌های گذرکرده از چهارراه اول، از تاریخ 2020/5/2 هر یک ساعت به یک ساعت جمع‌آوری شده است.
    <br>
    هدف این مسئه آن است که تعداد ماشین‌های گذرکننده از هر چهارراه را در هر ساعت از شبانه روز تخمین بزنیم. از آن جایی که شما هنوز با مدلسازی آشنا نیستید، از شما می‌خواهیم در مهندسی ویژگی‌ها به ما کمک کنید. در همین فایل نوت‌بوک سلول‌هایی برای مدلسازی قرار داده شده‌اند که شما نیازی نیست عملکرد آن‌ها را درک کنید، فقط آن‌ها را اجرا کنید و نتیجه پیش‌پردازش‌های خودتان را مشاهده کنید.
    <br>
    حال از شما می‌خواهیم با تکنیک‌هایی که در درسنامه‌های قبلی آموختید، به سنتز و تولید ویژگی بپردازید.
</font>
</p>

In [2]:
!pip install khayyam

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting khayyam
  Downloading Khayyam-3.0.17.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 KB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: khayyam
  Building wheel for khayyam (setup.py) ... done
  Created wheel for khayyam: filename=Khayyam-3.0.17-cp38-cp38-linux_x86_64.whl size=75161 sha256=f0ed55dbddc7663721d9940d8a10f4fa5bdeb63f5a914fe6ec0e28044aebee40
  Stored in directory: /root/.cache/pip/wheels/b0/b8/96/5db4fe1e98fcc9668c883856ef07219768e07fa2a85a95d2cc
Successfully built khayyam
Installing collected packages: khayyam
Successfully installed khayyam-3.0.17

In [3]:
!pip install flaml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting flaml
  Downloading FLAML-1.1.1-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.1/216.1 KB 8.7 MB/s eta 0:00:00
Requirement already satisfied: NumPy>=1.17.0rc1 in /usr/local/lib/python3.8/dist-packages (from flaml) (1.21.6)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.8/dist-packages (from flaml) (1.3.5)
Requirement already satisfied: xgboost>=0.90 in /usr/local/lib/python3.8/dist-packages (from flaml) (0.90)
Collecting lightgbm>=2.3.1
  Downloading lightgbm-3.3.5-py3-none-manylinux1_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 56.0 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=0.24 in /usr/local/lib/python3.8/dist-packages (from flaml) (1.0.2)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from flaml) (1.7.3)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from lightgbm>=2.3.1->flaml) (0.38.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.4->flaml) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.4->flaml) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.24->flaml) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.24->flaml) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1.4->flaml) (1.15.0)
Installing collected packages: lightgbm, flaml
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 2.2.3
    Uninstalling lightgbm-2.2.3:
      Successfully uninstalled lightgbm-2.2.3
Successfully installed flaml-1.1.1 lightgbm-3.3.5


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید و سپس مجموعه داده را از فایل بخوانید.
</font>
</p>

In [34]:
import numpy as np
import pandas as pd 
from khayyam import JalaliDatetime
from datetime import timedelta
import warnings
warnings.filterwarnings('ignore')
from flaml import AutoML
from sklearn.metrics import r2_score

In [5]:
from google.colab import files
uploaded = files.upload()

Saving traffic.csv to traffic.csv

In [35]:
# read csv file
import io
df = pd.read_csv(io.BytesIO(uploaded['traffic.csv']))
# df = pd.read_csv(r"C:\Users\STOCKLAND\Desktop\prohect_q\travel_times.csv")
df

                  DateTime  Junction  Car
0      2020-05-02 00:00:00         1   25
1      2020-05-02 01:00:00         1   23
2      2020-05-02 02:00:00         1   20
3      2020-05-02 03:00:00         1   12
4      2020-05-02 04:00:00         1   19
...                    ...       ...  ...
48115  2021-12-30 19:00:00         4   26
48116  2021-12-30 20:00:00         4   55
48117  2021-12-30 21:00:00         4   31
48118  2021-12-30 22:00:00         4   37
48119  2021-12-30 23:00:00         4   27

[48120 rows x 3 columns]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای آن که ارزش کار خود را درک کنید، نیاز است ابتدا که هیچگونه پیش‌پردازشی روی داده انجام نشده است، یکبار با آن مدلسازی کنید و عملکرد مدل را مشاهده کنید. با اجرای سلول زیر یک مدل روی داده آموزش می‌بیند و نتایجی تولید می‌کند.
    <br>
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    <ul>
        <li>
            کتابخانه Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
            در بارگزاری مجموعه داده دچار مشکل شده باشید.
        </li>
    </ul>
</font>
</div>

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DateTime  48120 non-null  object
 1   Junction  48120 non-null  int64
 2   Car       48120 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [37]:
df['DateTime']= pd.to_datetime(df['DateTime'])

In [38]:
model = AutoML(task='regression', time_budget=60, verbose=0)
train = df.loc[:48000]
test = df.loc[48000:]
model.fit(train.drop('Car', axis=1), train.Car)
y_pred = model.predict(test.drop('Car', axis=1))
r2score = round(r2_score(test.Car, y_pred),2) * 100 
print(f'performance of model is {r2score}%')

performance of model is 48.0%

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    متاسفانه دوربین‌هایی که در چهارراه‌ها نصب شده بودند، همگی وارداتی بوده اند. بنابراین به جای ثبت تاریخ، طبق تقویم جلالی (هجری شمسی)، تاریخ را به صورت میلادی ذخیره کرده‌است.
    <br>
    در اولین گام، از شما می‌خواهیم با استفاده از 
    <a href="https://khayyam.dobisel.com/">کتابخانه خیام</a>
    که برای کار با تقویم جلالی توسعه یافته‌است، همه تاریخ‌های میلادی را به تاریخ شمسی تبدیل کنید. به عبارت بهتر، معادل شمسی تاریخ‌هایی که در ستون <code>DateTime</code> دیتافریم <code>df</code> وجود دارند را درون ستون <code>JalaliDateTime</code> ذخیره کنید.
    <br>
    توجه داشته باشید، ستون <code>JalaliDateTime</code> در سلول جوابساز، به عنوان یکی از مولفه‌هایی که مورد داوری قرار می‌گیرند، از دیتافریم <code>df</code> استخراج می‌شود. بنابراین هیچ تغییری در ترتیب سطر‌ها و اسم ستون اعمال نکنید.
    <br>
    برای انجام راحت‌تر این قسمت و آشنایی بیشتر با کتابخانه خیام، سلول زیر را اجرا و نتیجه آن را مشاهده کنید.
    <br>
    به نحوه تغییر تاریخ میلادی به تاریخ شمسی توجه کنید!
</font>
</p>

In [39]:
from datetime import datetime as dt
miladi_date = dt(1998,10,29)
print(f'Miladi date = {miladi_date}')

from khayyam import JalaliDatetime
shamsi_date = JalaliDatetime(miladi_date)
print('Sahmsi date = ', shamsi_date)

Miladi date = 1998-10-29 00:00:00
Sahmsi date =  1377-08-07 00:00:00.000000

In [40]:
#TODO: convert gregorian datetime to jalali datatime
for date in df['DateTime']:
  df['JalaliDatetime'] = JalaliDatetime(date)
df

                 DateTime  Junction  Car              JalaliDatetime
0     2020-05-02 00:00:00         1   25  1400-10-09 23:00:00.000000
1     2020-05-02 01:00:00         1   23  1400-10-09 23:00:00.000000
2     2020-05-02 02:00:00         1   20  1400-10-09 23:00:00.000000
3     2020-05-02 03:00:00         1   12  1400-10-09 23:00:00.000000
4     2020-05-02 04:00:00         1   19  1400-10-09 23:00:00.000000
...                   ...       ...  ...                         ...
48115 2021-12-30 19:00:00         4   26  1400-10-09 23:00:00.000000
48116 2021-12-30 20:00:00         4   55  1400-10-09 23:00:00.000000
48117 2021-12-30 21:00:00         4   31  1400-10-09 23:00:00.000000
48118 2021-12-30 22:00:00         4   37  1400-10-09 23:00:00.000000
48119 2021-12-30 23:00:00         4   27  1400-10-09 23:00:00.000000

[48120 rows x 4 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    قصد داریم گسسته‌شده ساعتی که یک رکورد ثبت شده است را به عنوان ویژگی جدیدی به دیتافریم <code>df</code> اضافه کنیم. اسم این ستون را <code>hour</code> بگذارید.
    <br>
    به این منظور لازم است طبق جدول زیر، ساعات شبانه روز را گسسته کنیم.
    
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

|ساعت|دسته متناظر|
|------|------|
|از ۰۰:۰۰ تا ۵:۵۹:۵۹|0|
|از ۶:۰۰ تا ۱۱:۵۹:۵۹|1|
|از ۱۲:۰۰ تا ۱۴:۵۹:۵۹|2|
|از ۱۵:۰۰ تا ۱۷:۵۹:۵۹|3|
|از ۱۸:۰۰ تا ۲۱:۵۹:۵۹|4|
|از ۲۲:۰۰ تا ۲۳:۵۹:۵۹|5|
    
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    بازه‌هایی که در ستون ساعت در جدول بالا آمده است، از هر دو طرف بسته اند. یعنی وقتی می‌گوییم از ساعت ۰۰:۰۰ تا ۵:۵۹:۵۹ را به دسته 0 نگاشت کنید، به این معنی است که هم ساعت ۰۰:۰۰ و هم ساعت ۵:۵۹:۵۹ جز ساعاتی هستند که باید در دسته 0 قرار گیرند.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    توجه داشته باشید، ستون <code>hour</code> در سلول جوابساز، به عنوان یکی از مولفه‌هایی که مورد داوری قرار می‌گیرند، از دیتافریم <code>df</code> استخراج می‌شود. بنابراین هیچ تغییری در ترتیب سطر‌ها و اسم ستون اعمال نکنید.
 <br>
    دلیل انتخاب این ویژگی آن است که انتظار داریم تعداد ماشین‌هایی که در نیمه‌های شب در چهارراه‌ها تردد می‌کنند با تعداد ماشین‌هایی که از ساعت ۱۸ تا ۲۲ تردد می‌کنند، متفاوت باشد. البته درست آن است که با تحلیل داده و مصورسازی داده، این تفاوت عددی را توجیه کنیم. این کار را به عنوان تمرین بیشتر، به شما می‌سپاریم!
</font>
</p>

In [41]:
#TODO: add hour of record to dateset as a new column named `hour`
df['hour'] = df['DateTime'].dt.hour
df['hour'].astype('int')
for hour in df['hour']:
  if hour < 6:
    df['hour'] = 0
  elif hour >= 6 and hour < 12:
    df['hour'] = 1
  elif hour >= 12 and hour <15:
    df['hour'] = 2
  elif hour >= 15 and hour < 18:
    df['hour'] = 3
  elif hour >= 18 and hour < 22:
    df['hour'] = 4
  elif hour >= 22 and hour < 24:
    df['hour'] = 5
df

                 DateTime  Junction  Car              JalaliDatetime  hour
0     2020-05-02 00:00:00         1   25  1400-10-09 23:00:00.000000     0
1     2020-05-02 01:00:00         1   23  1400-10-09 23:00:00.000000     0
2     2020-05-02 02:00:00         1   20  1400-10-09 23:00:00.000000     0
3     2020-05-02 03:00:00         1   12  1400-10-09 23:00:00.000000     0
4     2020-05-02 04:00:00         1   19  1400-10-09 23:00:00.000000     0
...                   ...       ...  ...                         ...   ...
48115 2021-12-30 19:00:00         4   26  1400-10-09 23:00:00.000000     0
48116 2021-12-30 20:00:00         4   55  1400-10-09 23:00:00.000000     0
48117 2021-12-30 21:00:00         4   31  1400-10-09 23:00:00.000000     0
48118 2021-12-30 22:00:00         4   37  1400-10-09 23:00:00.000000     0
48119 2021-12-30 23:00:00         4   27  1400-10-09 23:00:00.000000     0

[48120 rows x 5 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در قسمت سوم از شما می‌خواهیم تعطیل بودن یا نبودن روز ثبت رکورد را تحت ستون جدیدی به اسم <code>IsHoliday</code> به دیتافریم اضافه کنید.
    <br>
    این ستون دارای دو مقدار ۰ و ۱ خواهد بود. در صورتی که روز ثبت رکورد، جمعه بوده باشد، این ستون ۱ و در غیر این صورت مقدار ۰ خواهد داشت.
    <br>
    علت انتخاب این ویژگی آن است که انتظار داریم، میزان تردد چهارراه‌ها در روز‌های تعطیل متفاوت از سایر روزها باشد. زیرا تعداد زیادی از ارگان‌ها مانند بانک‌ها یا مدارس، در روزهای تعطیل فعالیتی ندارند و کارمندی در آن‌ها مشغول به کار نیست. 
</font>
</p>

In [42]:
#TODO: determine whether it is a holiday or not. Add this feature to `df` as a new column named `IsHoliday`

df['IsHoliday'] = [holiday == 'Friday' for holiday in df['DateTime'].dt.day_name()]
df

,DateTime,Junction,Car,JalaliDatetime,hour,IsHoliday
0,2020-05-02 00:00:00,1,25,1400-10-09 23:00:00.000000,0,False
1,2020-05-02 01:00:00,1,23,1400-10-09 23:00:00.000000,0,False
2,2020-05-02 02:00:00,1,20,1400-10-09 23:00:00.000000,0,False
3,2020-05-02 03:00:00,1,12,1400-10-09 23:00:00.000000,0,False
4,2020-05-02 04:00:00,1,19,1400-10-09 23:00:00.000000,0,False
...,...,...,...,...,...,...
48115,2021-12-30 19:00:00,4,26,1400-10-09 23:00:00.000000,0,False
48116,2021-12-30 20:00:00,4,55,1400-10-09 23:00:00.000000,0,False
48117,2021-12-30 21:00:00,4,31,1400-10-09 23:00:00.000000,0,False
48118,2021-12-30 22:00:00,4,37,1400-10-09 23:00:00.000000,0,False
48119,2021-12-30 23:00:00,4,27,1400-10-09 23:00:00.000000,0,False

In [43]:
df['IsHoliday'].unique()

array([False,  True])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در قسمت چهارم این سوال می‌خواهیم بدانیم آیا یک رکورد در نیمه سرد سال ثبت شده است یا نیمه گرم سال. منظور از نیمه گرم سال، از شروع فروردین تا انتهای شهریور و منظور از نیمه سرد سال، از ابتدای مهر تا انتهای اسفند است.
    <br>
    اینکه یک رکورد در نیمه سرد سال ثبت شده باشد یا نه را به عنوان ستون جدیدی به اسم <code>IsCold</code> به دیتافریم <code>df</code> اضافه کنید.
    <br>
    این ستون فقط دو مقدار ۰ و ۱ قبول می‌کند. برای نیمه سرد سال عدد ۱ و برای نیمه گرم سال عدد ۰ را لحاظ کنید.
    <br>
    علت انتخاب این ویژگی آن است که در نیمه گرم سال، انتظار داریم مردم بیشتر با موتورسیکلت یا دوچرخه به تردد در شهر بپردازند و در نیمه سرد سال، برای حفاظت از سرما، بیشتر از اتوموبیل استفاده کنند.
</font>
</p>

In [44]:
#TODO: determinte whether it is cold or not. Add this feature to `df` as a new column named `IsCold`
hot_weather = ['March', 'April', 'May', 'June', 'July', 'August']
cold_weather = ['September', 'October', 'November', 'December', 'January', 'February']

df['IsCold'] = [month in hot_weather for month in df['DateTime'].dt.month_name()]

df

,DateTime,Junction,Car,JalaliDatetime,hour,IsHoliday,IsCold
0,2020-05-02 00:00:00,1,25,1400-10-09 23:00:00.000000,0,False,True
1,2020-05-02 01:00:00,1,23,1400-10-09 23:00:00.000000,0,False,True
2,2020-05-02 02:00:00,1,20,1400-10-09 23:00:00.000000,0,False,True
3,2020-05-02 03:00:00,1,12,1400-10-09 23:00:00.000000,0,False,True
4,2020-05-02 04:00:00,1,19,1400-10-09 23:00:00.000000,0,False,True
...,...,...,...,...,...,...,...
48115,2021-12-30 19:00:00,4,26,1400-10-09 23:00:00.000000,0,False,False
48116,2021-12-30 20:00:00,4,55,1400-10-09 23:00:00.000000,0,False,False
48117,2021-12-30 21:00:00,4,31,1400-10-09 23:00:00.000000,0,False,False
48118,2021-12-30 22:00:00,4,37,1400-10-09 23:00:00.000000,0,False,False
48119,2021-12-30 23:00:00,4,27,1400-10-09 23:00:00.000000,0,False,False

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت پنجم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    می‌دانیم که شماره چهارراه، یک متغیر گسسته اسمی است. بنابراین بهتر است آن را به شکل <code>one-hot-encoded</code> به دیتافریم <code>df</code> اضافه کنیم.
    <br>
    بنابراین با استفاده از ستون <code>Junction</code> چهار ستون با پیشوند <code>Junc</code> بسازید و آن‌ها را به دیتافریم <code>df</code> اضافه کنید.
    برای درک بهتر، تصور کنید این شش سطر زیر، بخشی از دیتافریم <code>df</code> باشند.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|Junction|
|-------|
|1|
|2|
|3|
|4|
|2|
|1|
    
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    انتظار داریم پس از انجام <code>one-hot-encode</code> چهار ستون مانند جدول زیر به ازای این ۶ سطر به دیتافریم <code>df</code> اضافه شوند.
</font>
</p>



<div style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|Junc_1|Junc_2|Junc_3|Junc_4|
|-------|-------|-------|-------|
|1|0|0|0|
|0|1|0|0|
|0|0|1|0|
|0|0|0|1|
|0|1|0|0|
|1|0|0|0|
    
</font>
</div>

In [45]:
#TODO: one-hot-encode the `Jucntion` column and add 4 columns to `df` with `Junc` prefix 
df = pd.get_dummies(df, columns = ['Junction'])
df

,DateTime,Car,JalaliDatetime,hour,IsHoliday,IsCold,Junction_1,Junction_2,Junction_3,Junction_4
0,2020-05-02 00:00:00,25,1400-10-09 23:00:00.000000,0,False,True,1,0,0,0
1,2020-05-02 01:00:00,23,1400-10-09 23:00:00.000000,0,False,True,1,0,0,0
2,2020-05-02 02:00:00,20,1400-10-09 23:00:00.000000,0,False,True,1,0,0,0
3,2020-05-02 03:00:00,12,1400-10-09 23:00:00.000000,0,False,True,1,0,0,0
4,2020-05-02 04:00:00,19,1400-10-09 23:00:00.000000,0,False,True,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
48115,2021-12-30 19:00:00,26,1400-10-09 23:00:00.000000,0,False,False,0,0,0,1
48116,2021-12-30 20:00:00,55,1400-10-09 23:00:00.000000,0,False,False,0,0,0,1
48117,2021-12-30 21:00:00,31,1400-10-09 23:00:00.000000,0,False,False,0,0,0,1
48118,2021-12-30 22:00:00,37,1400-10-09 23:00:00.000000,0,False,False,0,0,0,1
48119,2021-12-30 23:00:00,27,1400-10-09 23:00:00.000000,0,False,False,0,0,0,1

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

In [ ]:
import zipfile
import joblib

synthesized_cols = ['JalaliDateTime', 'hour', 'IsHoliday', 'IsCold', 'Junc_1', 'Junc_2', 'Junc_3', 'Junc_4']

submision_df = df[synthesized_cols]

submision_df.to_csv('df.csv', index=False)


def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["df.csv", "traffic_shahri.ipynb"]
compress(file_names)


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از اجرای سلول بالا، می‌توانید برای کسب نمره، فایل results.zip را برای سامانه داوری ارسال کنید.
    <br>
    اگر تمایل به مشاهده تاثیر پیش‌پردازش‌های انجام‌شده دارید، سلول‌های زیر را اجرا کنید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدلسازی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال که سوالات را حل کردید، پیشنهاد می‌کنیم مجددا روی مجموعه‌داده جدیدی که به دست آوردید، مدلسازی کنید تا تاثیر پیش‌پردازش را در نتیجه نهایی مشاهده کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای انجام مدلسازی دوباره، فقط کافیست سلول زیر را اجرا کنید.
    <br>
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    <ul>
        <li>
            کتابخانه Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
           پیش‌پردازش‌های توضیح داده‌شده را اشتباه انجام داده باشید.
        </li>
    </ul>
</font>
</div>

In [46]:
model = AutoML(task='regression', time_budget=60, verbose=0)
useful_cols = ['DateTime', 'hour', 'IsHoliday', 'IsCold', 'Junction_1', 'Junction_2', 'Junction_3', 'Junction_4', 'Car']
train = df[useful_cols].loc[:48000]
test = df[useful_cols].loc[48000:]
model.fit(train.drop('Car', axis=1), np.log(train.Car))
y_pred = np.exp(model.predict(test.drop('Car', axis=1)))
r2score = round(r2_score(test.Car, y_pred),2) * 100 
print(f'performance of model is {r2score}%')

performance of model is 57.99999999999999%